name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm i
        working-directory: react
      - run: npm run lint
        working-directory: react
      - run: npm run format -- --check
        working-directory: react

      - uses: denoland/setup-deno@v2
        with:
          deno-version: latest
      - run: deno lint functions
        working-directory: supabase
      - run: deno fmt --check functions
        working-directory: supabase